//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.Shipping.Correios.wsRastro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://resource.webservice.correios.com.br/", ConfigurationName="wsRastro.Service")]
    public interface Service {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventos", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse buscaEventos(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventos", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosResponse")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse> buscaEventosAsync(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventosLista", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse buscaEventosLista(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventosLista", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse> buscaEventosListaAsync(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="RastroJson", ReplyAction="http://resource.webservice.correios.com.br/Service/RastroJsonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse RastroJson(Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RastroJson", ReplyAction="http://resource.webservice.correios.com.br/Service/RastroJsonResponse")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse> RastroJsonAsync(Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="ListaEntregaExterna", ReplyAction="http://resource.webservice.correios.com.br/Service/ListaEntregaExternaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse ListaEntregaExterna(Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ListaEntregaExterna", ReplyAction="http://resource.webservice.correios.com.br/Service/ListaEntregaExternaResponse")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse> ListaEntregaExternaAsync(Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="UnidadesSRO", ReplyAction="http://resource.webservice.correios.com.br/Service/UnidadesSROResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse UnidadesSRO(Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UnidadesSRO", ReplyAction="http://resource.webservice.correios.com.br/Service/UnidadesSROResponse")]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse> UnidadesSROAsync(Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class sroxml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoField;
        
        private string qtdField;
        
        private string tipoPesquisaField;
        
        private string tipoResultadoField;
        
        private objeto[] objetoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string versao {
            get {
                return versaoField;
            }
            set {
                versaoField = value;
                RaisePropertyChanged("versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string qtd {
            get {
                return qtdField;
            }
            set {
                qtdField = value;
                RaisePropertyChanged("qtd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoPesquisa {
            get {
                return tipoPesquisaField;
            }
            set {
                tipoPesquisaField = value;
                RaisePropertyChanged("TipoPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TipoResultado {
            get {
                return tipoResultadoField;
            }
            set {
                tipoResultadoField = value;
                RaisePropertyChanged("TipoResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objeto", Order=4)]
        public objeto[] objeto {
            get {
                return objetoField;
            }
            set {
                objetoField = value;
                RaisePropertyChanged("objeto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class objeto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string siglaField;
        
        private string nomeField;
        
        private string categoriaField;
        
        private string erroField;
        
        private eventos[] eventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return numeroField;
            }
            set {
                numeroField = value;
                RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sigla {
            get {
                return siglaField;
            }
            set {
                siglaField = value;
                RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return nomeField;
            }
            set {
                nomeField = value;
                RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string categoria {
            get {
                return categoriaField;
            }
            set {
                categoriaField = value;
                RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string erro {
            get {
                return erroField;
            }
            set {
                erroField = value;
                RaisePropertyChanged("erro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evento", Order=5)]
        public eventos[] evento {
            get {
                return eventoField;
            }
            set {
                eventoField = value;
                RaisePropertyChanged("evento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class eventos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string statusField;
        
        private string dataField;
        
        private string horaField;
        
        private string descricaoField;
        
        private string detalheField;
        
        private string recebedorField;
        
        private string documentoField;
        
        private string comentarioField;
        
        private string localField;
        
        private string codigoField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string stoField;
        
        private string amazoncodeField;
        
        private string amazontimezoneField;
        
        private destinos[] destinoField;
        
        private enderecoMobile enderecoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipo {
            get {
                return tipoField;
            }
            set {
                tipoField = value;
                RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return statusField;
            }
            set {
                statusField = value;
                RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string data {
            get {
                return dataField;
            }
            set {
                dataField = value;
                RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string hora {
            get {
                return horaField;
            }
            set {
                horaField = value;
                RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descricao {
            get {
                return descricaoField;
            }
            set {
                descricaoField = value;
                RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string detalhe {
            get {
                return detalheField;
            }
            set {
                detalheField = value;
                RaisePropertyChanged("detalhe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string recebedor {
            get {
                return recebedorField;
            }
            set {
                recebedorField = value;
                RaisePropertyChanged("recebedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string documento {
            get {
                return documentoField;
            }
            set {
                documentoField = value;
                RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string comentario {
            get {
                return comentarioField;
            }
            set {
                comentarioField = value;
                RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string local {
            get {
                return localField;
            }
            set {
                localField = value;
                RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codigo {
            get {
                return codigoField;
            }
            set {
                codigoField = value;
                RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cidade {
            get {
                return cidadeField;
            }
            set {
                cidadeField = value;
                RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string uf {
            get {
                return ufField;
            }
            set {
                ufField = value;
                RaisePropertyChanged("uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string sto {
            get {
                return stoField;
            }
            set {
                stoField = value;
                RaisePropertyChanged("sto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string amazoncode {
            get {
                return amazoncodeField;
            }
            set {
                amazoncodeField = value;
                RaisePropertyChanged("amazoncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string amazontimezone {
            get {
                return amazontimezoneField;
            }
            set {
                amazontimezoneField = value;
                RaisePropertyChanged("amazontimezone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("destino", Order=16)]
        public destinos[] destino {
            get {
                return destinoField;
            }
            set {
                destinoField = value;
                RaisePropertyChanged("destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public enderecoMobile endereco {
            get {
                return enderecoField;
            }
            set {
                enderecoField = value;
                RaisePropertyChanged("endereco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class destinos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string localField;
        
        private string codigoField;
        
        private string cidadeField;
        
        private string bairroField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string local {
            get {
                return localField;
            }
            set {
                localField = value;
                RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return codigoField;
            }
            set {
                codigoField = value;
                RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cidade {
            get {
                return cidadeField;
            }
            set {
                cidadeField = value;
                RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bairro {
            get {
                return bairroField;
            }
            set {
                bairroField = value;
                RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string uf {
            get {
                return ufField;
            }
            set {
                ufField = value;
                RaisePropertyChanged("uf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class registroUnidades : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoDRField;
        
        private string codigoMCUField;
        
        private string codigoSROField;
        
        private string nomeUnidadeField;
        
        private string siglaDRField;
        
        private string siglaTipoUnidadeField;
        
        private string tipoUnidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDR {
            get {
                return codigoDRField;
            }
            set {
                codigoDRField = value;
                RaisePropertyChanged("codigoDR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoMCU {
            get {
                return codigoMCUField;
            }
            set {
                codigoMCUField = value;
                RaisePropertyChanged("codigoMCU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSRO {
            get {
                return codigoSROField;
            }
            set {
                codigoSROField = value;
                RaisePropertyChanged("codigoSRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nomeUnidade {
            get {
                return nomeUnidadeField;
            }
            set {
                nomeUnidadeField = value;
                RaisePropertyChanged("nomeUnidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string siglaDR {
            get {
                return siglaDRField;
            }
            set {
                siglaDRField = value;
                RaisePropertyChanged("siglaDR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string siglaTipoUnidade {
            get {
                return siglaTipoUnidadeField;
            }
            set {
                siglaTipoUnidadeField = value;
                RaisePropertyChanged("siglaTipoUnidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoUnidade {
            get {
                return tipoUnidadeField;
            }
            set {
                tipoUnidadeField = value;
                RaisePropertyChanged("tipoUnidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class objetoPostal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agrupamentoField;
        
        private string avisoRecebimentoField;
        
        private string devolucaoDocumentoField;
        
        private string devolucaoObjetoField;
        
        private string maoPropriaField;
        
        private string numeroObjetoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agrupamento {
            get {
                return agrupamentoField;
            }
            set {
                agrupamentoField = value;
                RaisePropertyChanged("agrupamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string avisoRecebimento {
            get {
                return avisoRecebimentoField;
            }
            set {
                avisoRecebimentoField = value;
                RaisePropertyChanged("avisoRecebimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string devolucaoDocumento {
            get {
                return devolucaoDocumentoField;
            }
            set {
                devolucaoDocumentoField = value;
                RaisePropertyChanged("devolucaoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string devolucaoObjeto {
            get {
                return devolucaoObjetoField;
            }
            set {
                devolucaoObjetoField = value;
                RaisePropertyChanged("devolucaoObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string maoPropria {
            get {
                return maoPropriaField;
            }
            set {
                maoPropriaField = value;
                RaisePropertyChanged("maoPropria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroObjeto {
            get {
                return numeroObjetoField;
            }
            set {
                numeroObjetoField = value;
                RaisePropertyChanged("numeroObjeto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class listaEntregaExterna : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string carteiroField;
        
        private System.DateTime dataField;
        
        private bool dataFieldSpecified;
        
        private string distritoField;
        
        private string estacaoField;
        
        private string idField;
        
        private string loecField;
        
        private string nomeCarteiroField;
        
        private string nomeUnidadeField;
        
        private objetoPostal[] objetosField;
        
        private string unidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string carteiro {
            get {
                return carteiroField;
            }
            set {
                carteiroField = value;
                RaisePropertyChanged("carteiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime data {
            get {
                return dataField;
            }
            set {
                dataField = value;
                RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSpecified {
            get {
                return dataFieldSpecified;
            }
            set {
                dataFieldSpecified = value;
                RaisePropertyChanged("dataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string distrito {
            get {
                return distritoField;
            }
            set {
                distritoField = value;
                RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estacao {
            get {
                return estacaoField;
            }
            set {
                estacaoField = value;
                RaisePropertyChanged("estacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string id {
            get {
                return idField;
            }
            set {
                idField = value;
                RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string loec {
            get {
                return loecField;
            }
            set {
                loecField = value;
                RaisePropertyChanged("loec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nomeCarteiro {
            get {
                return nomeCarteiroField;
            }
            set {
                nomeCarteiroField = value;
                RaisePropertyChanged("nomeCarteiro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nomeUnidade {
            get {
                return nomeUnidadeField;
            }
            set {
                nomeUnidadeField = value;
                RaisePropertyChanged("nomeUnidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objetos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public objetoPostal[] objetos {
            get {
                return objetosField;
            }
            set {
                objetosField = value;
                RaisePropertyChanged("objetos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string unidade {
            get {
                return unidadeField;
            }
            set {
                unidadeField = value;
                RaisePropertyChanged("unidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class enderecoMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string cepField;
        
        private string logradouroField;
        
        private string complementoField;
        
        private string numeroField;
        
        private string localidadeField;
        
        private string ufField;
        
        private string bairroField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string celularField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return codigoField;
            }
            set {
                codigoField = value;
                RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cep {
            get {
                return cepField;
            }
            set {
                cepField = value;
                RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string logradouro {
            get {
                return logradouroField;
            }
            set {
                logradouroField = value;
                RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string complemento {
            get {
                return complementoField;
            }
            set {
                complementoField = value;
                RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numero {
            get {
                return numeroField;
            }
            set {
                numeroField = value;
                RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localidade {
            get {
                return localidadeField;
            }
            set {
                localidadeField = value;
                RaisePropertyChanged("localidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string uf {
            get {
                return ufField;
            }
            set {
                ufField = value;
                RaisePropertyChanged("uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string bairro {
            get {
                return bairroField;
            }
            set {
                bairroField = value;
                RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string latitude {
            get {
                return latitudeField;
            }
            set {
                latitudeField = value;
                RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string longitude {
            get {
                return longitudeField;
            }
            set {
                longitudeField = value;
                RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string celular {
            get {
                return celularField;
            }
            set {
                celularField = value;
                RaisePropertyChanged("celular");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventos", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lingua;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objetos;
        
        public buscaEventosRequest() {
        }
        
        public buscaEventosRequest(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            this.usuario = usuario;
            this.senha = senha;
            this.tipo = tipo;
            this.resultado = resultado;
            this.lingua = lingua;
            this.objetos = objetos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.Shipping.Correios.wsRastro.sroxml @return;
        
        public buscaEventosResponse() {
        }
        
        public buscaEventosResponse(Nop.Plugin.Shipping.Correios.wsRastro.sroxml @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosLista", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lingua;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("objetos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] objetos;
        
        public buscaEventosListaRequest() {
        }
        
        public buscaEventosListaRequest(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            this.usuario = usuario;
            this.senha = senha;
            this.tipo = tipo;
            this.resultado = resultado;
            this.lingua = lingua;
            this.objetos = objetos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosListaResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.Shipping.Correios.wsRastro.sroxml @return;
        
        public buscaEventosListaResponse() {
        }
        
        public buscaEventosListaResponse(Nop.Plugin.Shipping.Correios.wsRastro.sroxml @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RastroJson", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class RastroJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lingua;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objetos;
        
        public RastroJsonRequest() {
        }
        
        public RastroJsonRequest(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            this.usuario = usuario;
            this.senha = senha;
            this.tipo = tipo;
            this.resultado = resultado;
            this.lingua = lingua;
            this.objetos = objetos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RastroJsonResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class RastroJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public RastroJsonResponse() {
        }
        
        public RastroJsonResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaEntregaExterna", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class ListaEntregaExternaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loec;
        
        public ListaEntregaExternaRequest() {
        }
        
        public ListaEntregaExternaRequest(string loec) {
            this.loec = loec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaEntregaExternaResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class ListaEntregaExternaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.Shipping.Correios.wsRastro.listaEntregaExterna @return;
        
        public ListaEntregaExternaResponse() {
        }
        
        public ListaEntregaExternaResponse(Nop.Plugin.Shipping.Correios.wsRastro.listaEntregaExterna @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnidadesSRO", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class UnidadesSRORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSRO;
        
        public UnidadesSRORequest() {
        }
        
        public UnidadesSRORequest(string codigoSRO) {
            this.codigoSRO = codigoSRO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnidadesSROResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class UnidadesSROResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.Shipping.Correios.wsRastro.registroUnidades[] @return;
        
        public UnidadesSROResponse() {
        }
        
        public UnidadesSROResponse(Nop.Plugin.Shipping.Correios.wsRastro.registroUnidades[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceChannel : Nop.Plugin.Shipping.Correios.wsRastro.Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Nop.Plugin.Shipping.Correios.wsRastro.Service>, Nop.Plugin.Shipping.Correios.wsRastro.Service {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse Nop.Plugin.Shipping.Correios.wsRastro.Service.buscaEventos(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest request) {
            return base.Channel.buscaEventos(request);
        }
        
        public Nop.Plugin.Shipping.Correios.wsRastro.sroxml buscaEventos(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse retVal = ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).buscaEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse> Nop.Plugin.Shipping.Correios.wsRastro.Service.buscaEventosAsync(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest request) {
            return base.Channel.buscaEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosResponse> buscaEventosAsync(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            return ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).buscaEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse Nop.Plugin.Shipping.Correios.wsRastro.Service.buscaEventosLista(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest request) {
            return base.Channel.buscaEventosLista(request);
        }
        
        public Nop.Plugin.Shipping.Correios.wsRastro.sroxml buscaEventosLista(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse retVal = ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).buscaEventosLista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse> Nop.Plugin.Shipping.Correios.wsRastro.Service.buscaEventosListaAsync(Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest request) {
            return base.Channel.buscaEventosListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaResponse> buscaEventosListaAsync(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.buscaEventosListaRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            return ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).buscaEventosListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse Nop.Plugin.Shipping.Correios.wsRastro.Service.RastroJson(Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest request) {
            return base.Channel.RastroJson(request);
        }
        
        public string RastroJson(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse retVal = ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).RastroJson(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse> Nop.Plugin.Shipping.Correios.wsRastro.Service.RastroJsonAsync(Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest request) {
            return base.Channel.RastroJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonResponse> RastroJsonAsync(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.RastroJsonRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            return ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).RastroJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse Nop.Plugin.Shipping.Correios.wsRastro.Service.ListaEntregaExterna(Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest request) {
            return base.Channel.ListaEntregaExterna(request);
        }
        
        public Nop.Plugin.Shipping.Correios.wsRastro.listaEntregaExterna ListaEntregaExterna(string loec) {
            Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest();
            inValue.loec = loec;
            Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse retVal = ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).ListaEntregaExterna(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse> Nop.Plugin.Shipping.Correios.wsRastro.Service.ListaEntregaExternaAsync(Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest request) {
            return base.Channel.ListaEntregaExternaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaResponse> ListaEntregaExternaAsync(string loec) {
            Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.ListaEntregaExternaRequest();
            inValue.loec = loec;
            return ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).ListaEntregaExternaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse Nop.Plugin.Shipping.Correios.wsRastro.Service.UnidadesSRO(Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest request) {
            return base.Channel.UnidadesSRO(request);
        }
        
        public Nop.Plugin.Shipping.Correios.wsRastro.registroUnidades[] UnidadesSRO(string codigoSRO) {
            Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest();
            inValue.codigoSRO = codigoSRO;
            Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse retVal = ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).UnidadesSRO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse> Nop.Plugin.Shipping.Correios.wsRastro.Service.UnidadesSROAsync(Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest request) {
            return base.Channel.UnidadesSROAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSROResponse> UnidadesSROAsync(string codigoSRO) {
            Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest inValue = new Nop.Plugin.Shipping.Correios.wsRastro.UnidadesSRORequest();
            inValue.codigoSRO = codigoSRO;
            return ((Nop.Plugin.Shipping.Correios.wsRastro.Service)(this)).UnidadesSROAsync(inValue);
        }
    }
}
